# Generated by Django 3.0.4 on 2020-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion_de_la_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.IntegerField(verbose_name=9),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='codigoproceso',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
