# Generated by Django 3.0.4 on 2020-04-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion_de_la_produccion', '0002_auto_20200419_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
