# Generated by Django 3.0.5 on 2020-04-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion_de_la_produccion', '0004_auto_20200419_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='empleados_asignados',
            field=models.ManyToManyField(to='appGestion_de_la_produccion.Empleado'),
        ),
    ]
