# Generated by Django 3.0.5 on 2020-04-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion_de_la_produccion', '0005_proceso_empleados_asignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appGestion_de_la_produccion.Equipo'),
            preserve_default=False,
        ),
    ]
