# Generated by Django 3.0.5 on 2020-04-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion_de_la_produccion', '0007_empleado_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fecha_adquision',
            new_name='fecha_adquisicion',
        ),
    ]
